config/routes.rb
Rails.application.routes.draw do
  root to: 'home_pages#show'
  get '/home', to: redirect('/')

  resources :projects, only: [:index, :show]
  resources :brush_strokes, only: [:create]

  namespace :admin do
    resources :brush_strokes
    resources :projects
  end
end

app/models/project.rb
class Project < Forest::ApplicationRecord
  include Blockable
  include Sluggable
  include Statusable

  belongs_to :media_item
  belongs_to :video_item, class_name: 'MediaItem', optional: true
  belongs_to :video_item_mobile, class_name: 'MediaItem', optional: true

  def self.resource_description
    'Labud\'s projects!'
  end

  def to_page_title
    [title, subtitle].reject(&:blank?).join(' - ')
  end

  def pretty_website_url
    URI.parse(url).host.sub(/^www\./, '') unless url.blank?
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ForestController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = apply_scopes(Project).by_id.page(params[:page])
  end

  def show
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project

    if @project.save
      redirect_to edit_admin_project_path(@project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @project

    if @project.update(project_params)
      redirect_to edit_admin_project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to admin_projects_url, notice: 'Project was successfully destroyed.'
  end

  private

    def project_params
      # Add blockable params to the permitted attributes if this record is blockable `**BlockSlot.blockable_params`
      params.require(:project).permit(:slug, :status, :title, :subtitle, :description, :metadata, :media_item_id,
        :page_color, :url, :video_item_id, :video_item_mobile_id, :dark_featured_media, **BlockSlot.blockable_params)
    end

    def set_project
      @project = Project.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ForestController
  before_action :set_project, only: [:show]

  def index
    # TODO: published/statusable scope
    @projects = apply_scopes(Project)
  end

  def show
    authorize @project
    @body_styles ||= []
    @body_classes ||= []

    if @project.page_color.present?
      @body_styles << "background-color: #{@project.page_color};"
    end

    if @project.dark_featured_media.present?
      @body_classes << 'inverse-header'
    end
  end

  private

    def set_project
      @project = Project.find_by!(slug: params[:id])
    end
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, @project]) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default" data-collapse-parent>
        <div class="panel-heading">
          <h3 class="panel-title">
            Metadata
            <button type="button" class="btn btn-default btn-xs pull-right" data-collapse-trigger>
              <div class="collapsable-icon glyphicon glyphicon-chevron-up"></div>
            </button>
          </h3>
        </div>
        <div class="panel-body" data-collapse-body>
          <div class="form-inputs">
            <div class="row">
              <div class="col-sm-6">
                <%= render 'admin/form_inputs/slug', f: f %>
                <%= f.input :title %>
                <%= f.input :subtitle %>
                <%= f.input :description, markdown: true %>
                <%= f.input :metadata, markdown: true %>
                <%= f.button :submit, class: 'btn-success' %>
              </div>
              <div class="col-sm-6">
                <%= render 'admin/form_inputs/status', f: f, record: @project %>
                <%= f.input :page_color, as: :color, default: '#ffffff' %>
                <%= f.input :url, label: 'Website URL' %>
                <%= f.association :video_item, label: 'Video', remote: { path: admin_media_items_path(videos: true) } %>
                <%= f.association :video_item_mobile, label: 'Video (mobile)', remote: { path: admin_media_items_path(videos: true) } %>
                <%= f.association :media_item, as: :image, label: 'Featured image or poster image', hint: 'This is used as the poster image when the project has a video.' %>
                <%= f.input :dark_featured_media, hint: 'Set this to true if the featured image or video is dark. This will make the header white when at the top of a project.' %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <%= render 'admin/block_record/block_layout', f: f, block_layout: @block_layout, block_kinds: @block_kinds %>
      <%= f.button :submit, class: 'btn-success' %>

    </div>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<%= render 'admin/headers/edit', record: @project %>

<%= render 'form', record: @project %>

app/views/admin/projects/index.html.erb
<%= render 'admin/headers/index', records: @projects, model_name: 'Project' %>

<div class="table-responsive">
  <table class="forest-table table table-striped">
    <thead>
      <tr>
        <% if Project.statusable? %>
          <th></th>
        <% end %>
        <th><%= table_sorter title: 'ID', path: :admin_projects_path, scope: :by_id, default_order: :desc %></th>
        <th>Media Item</th>
        <th><%= table_sorter title: 'Slug', path: :admin_projects_path, scope: :by_slug, default_order: :asc %></th>
        <th>Title</th>
        <th>Subtitle</th>
        <th><%= table_sorter title: 'Created&nbsp;at'.html_safe, path: :admin_projects_path, scope: :by_created_at, default_order: :desc %></th>
        <th><%= table_sorter title: 'Updated&nbsp;at'.html_safe, path: :admin_projects_path, scope: :by_updated_at, default_order: :desc %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <% if Project.statusable? %>
            <td><%= status_indicator project %></td>
          <% end %>
          <td><%= project.id %></td>
          <td><%= table_thumbnail project.media_item %></td>
          <td><%= project.slug %></td>
          <td><%= project.title %></td>
          <td><%= project.subtitle %></td>
          <td><%= forest_date project.created_at %></td>
          <td><%= forest_date project.updated_at %></td>
          <td width="1"><%= link_to 'Edit', edit_admin_project_path(project), class: 'btn btn-xs btn-primary', role: 'button' %></td>
          <td width="1">
            <% if try('project_path', project) %>
              <% if project.respond_to?(:to_friendly_param) %>
                <% param = project.to_friendly_param %>
              <% else %>
                <% param = project %>
              <% end %>
              <%= link_to 'Show', project_path(param), class: 'btn btn-xs btn-info', role: 'button', data: { turbolinks: false } %>
            <% else %>
              <%= link_to 'Show', admin_project_path(project), class: 'btn btn-xs btn-info', role: 'button', data: { turbolinks: false } %>
            <% end %>
          </td>
          <td width="1"><%= link_to 'Destroy', [:admin, project], method: :delete, class: 'btn btn-xs btn-danger', role: 'button', data: { confirm: 'Are you sure you want to destroy this Project?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @projects %>

app/views/admin/projects/new.html.erb
<%= render 'admin/headers/new', record: @project %>

<%= render 'form', project: @project %>

app/views/admin/projects/show.html.erb
<p>Find me in app/views/forest/projects/show.html.erb</p>

<%# content_for :page_description, @project.description if @project.try(:description).present? %>

<p>
  <b>Title</b>
  <%= @project.title %>
</p>
<p>
  <b>Subtitle</b>
  <%= @project.subtitle %>
</p>
<p>
  <b>Description</b>
  <%= @project.description %>
</p>
<p>
  <b>Metadata</b>
  <%= @project.metadata %>
</p>
<p>
  <b>Media Item</b>
  <%= @project.media_item %>
</p>

<%= render_blocks @project %>